const state = {
  links: [{
    name: "上大",
    buttons: [{
      name: "上大主页",
      desktop: "http://www.shu.edu.cn/",
      mobile: "http://www.shu.edu.cn/",
      color: "#1F437C",
      icon: "SHU"
    }, {
      name: "开源社区",
      desktop: "https://osc.shu.edu.cn/",
      mobile: "https://osc.shu.edu.cn/",
      color: "#48BEA1",
      icon: "SHUOSC"
    }, {
      name: "SHUhelper",
      desktop: "https://www.shuhelper.cn",
      mobile: "https://www.shuhelper.cn",
      color: "#03A9F4",
    }, {
      name: "上大邮箱",
      desktop: "http://newmail.shu.edu.cn/",
      mobile: "http://newmail.shu.edu.cn/coremail/xphone/index.jsp",
      color: "#3388FF",
      icon: "mail"
    }, {
      name: "图书馆",
      desktop: "http://www.lib.shu.edu.cn/",
      mobile: "http://www.lib.shu.edu.cn/",
      color: "#3663A1",
      icon: "library"
    }, {
      name: "乐乎论坛",
      desktop: "http://www.lehu.shu.edu.cn/",
      mobile: "http://www.lehu.shu.edu.cn/",
      color: "#FF9619"
    }]
  }, {
    name: "学习",
    buttons: [{
      name: "知网",
      desktop: "http://cnki.net/",
      mobile: "http://wap.cnki.net/",
      color: "#115FAD",
      icon: "CNKI"
    }, {
      name: "谷歌学术",
      desktop: 'https://scholar.google.com/',
      mobile: 'https://scholar.google.com/',
      color: "#FBBC05",
      icon: "GoogleScholar"
    }, {
      name: "中国大学MOOC",
      desktop: 'http://www.icourse163.org/',
      mobile: 'http://www.icourse163.org',
      color: "#51A128",
    }, {
      name: "网易公开课",
      desktop: 'https://open.163.com/',
      mobile: 'https://m.open.163.com/',
      color: "#286A46",
      icon: "gongkaike"
    }, {
      name: "Coursera",
      desktop: 'https://zh.coursera.org/',
      mobile: 'https://zh.coursera.org/',
      color: "#4A89DC",
      icon: "coursera"
    }, {
      name: "edX",
      desktop: 'https://www.edx.org/',
      mobile: 'https://www.edx.org/',
      color: "#B72667"
    }, {
      name: "慕课网",
      desktop: 'http://www.imooc.com/',
      mobile: 'http://m.imooc.com/',
      color: "#F01414",
      icon: "mukewang"
    }, {
      name: "网易云课堂",
      desktop: 'https://study.163.com/',
      mobile: 'https://m.study.163.com/',
      color: "#309225",
    }, {
      name: "TED",
      desktop: 'https://www.ted.com/',
      mobile: 'https://www.ted.com/',
      color: "#E62B1E"
    }, {
      name: "MIT OCW",
      desktop: 'https://ocw.mit.edu/',
      mobile: 'https://ocw.mit.edu/',
      color: "#B30838"
    }, {
      name: "GitHub",
      desktop: 'https://www.github.com',
      mobile: 'https://www.github.com',
      color: "#24292E",
      icon: "GitHub"
    }, {
      name: "StackOverflow",
      desktop: 'https://stackoverflow.com/',
      mobile: 'https://stackoverflow.com/',
      color: "#F48024",
      icon: "StackOverflow"
    }]
  }, {
    name: "社交",
    buttons: [{
      name: "Web微信",
      desktop: 'https://wx.qq.com/',
      mobile: 'https://wx.qq.com/',
      color: "#41990C",
      icon: "weixin"
    }, {
      name: "WebQQ",
      desktop: 'https://w.qq.com/',
      mobile: 'https://w.qq.com/',
      color: "#65B4E0",
      icon: "qq"
    }, {
      name: "微博",
      desktop: 'http://weibo.com/',
      mobile: 'http://weibo.com/',
      color: "#FF8140",
      icon: "Weibo"
    }, {
      name: "百度贴吧",
      desktop: 'https://tieba.baidu.com',
      mobile: 'https://tieba.baidu.com/',
      color: "#1D11D8",
      icon: "tieba"
    }, {
      name: "知乎",
      desktop: 'https://www.zhihu.com/',
      mobile: 'https://www.zhihu.com/',
      color: "#0F88EB",
      icon: "zh"
    }, {
      name: "豆瓣",
      desktop: 'https://www.douban.com/',
      mobile: 'https://m.douban.com/',
      color: "#2E963D",
      icon: "db"
    }, {
      name: "Facebook",
      desktop: 'https://www.facebook.com/',
      mobile: 'https://m.facebook.com/',
      color: "#3B5998",
      icon: "facebook"
    }, {
      name: "Instagram",
      desktop: 'https://www.instagram.com/',
      mobile: 'https://www.instagram.com/',
      color: "#ED4856",
      icon: "ins"
    }, {
      name: "Quora",
      desktop: 'https://www.quora.com/',
      mobile: 'https://www.quora.com/',
      color: "#B92B27",
      icon: "quora"
    }, {
      name: "Google+",
      desktop: 'https://plus.google.com/',
      mobile: 'https://plus.google.com/',
      color: "#DE5E53",
      icon: "googleplus"
    }, {
      name: "Twitter",
      desktop: 'https://twitter.com/',
      mobile: 'https://mobile.twitter.com/',
      color: "#1DA1F2",
      icon: "twitter"
    }, {
      name: "WhatsApp",
      desktop: 'https://web.whatsapp.com/',
      mobile: 'https://web.whatsapp.com/',
      color: "#43D854",
      icon: "whatsapp"
    }]
  }, {
    name: "工具",
    buttons: [{
      name: "12306",
      desktop: 'http://www.12306.cn/',
      mobile: 'http://www.12306.cn/',
      color: "#BA2636",
      icon: "12306"
    }, {
      name: "谷歌翻译",
      desktop: 'https://translate.google.cn/',
      mobile: 'https://translate.google.cn/m/translate',
      color: "#498BF4",
      icon: "gTranslate"
    }, {
      name: "维基百科",
      desktop: 'https://zh.wikipedia.org/',
      mobile: 'https://zh.m.wikipedia.org/',
      color: "#6B6B6B",
      icon: "Wikipedia"
    }, {
      name: "腾讯企业邮",
      desktop: 'https://exmail.qq.com/cgi-bin/loginpage',
      mobile: 'https://m.exmail.qq.com/cgi-bin/loginpage',
      color: "#017CC0",
      icon: "tencentMail"
    }, {
      name: "网易企业邮",
      desktop: 'https://qiye.163.com/login/',
      mobile: 'https://qiye.163.com/m/login.htm',
      color: "#B61820",
      icon: "wangyi"
    }, {
      name: "163邮箱",
      desktop: 'http://mail.163.com/',
      mobile: 'http://smart.mail.163.com/?dv=smart',
      color: "#D90000",
      icon: "wangyi"
    }, {
      name: "126邮箱",
      desktop: 'http://mail.126.com/',
      mobile: 'http://smart.mail.126.com/?dv=smart',
      color: "#158144",
      icon: "wangyi"
    }, {
      name: "Outlook邮箱",
      desktop: 'https://outlook.live.com/owa/',
      mobile: 'https://outlook.live.com/owa/',
      color: "#0078D7",
      icon: "outlook"
    }, {
      name: "iCloud邮箱",
      desktop: 'https://www.icloud.com/',
      mobile: 'https://www.icloud.com/',
      color: "#000000",
      icon: "apple"
    }, {
      name: "Gmail",
      desktop: 'https://mail.google.com/',
      mobile: 'https://mail.google.com/',
      color: "#DD5044",
      icon: "gmail"
    }, {
      name: "QQ邮箱",
      desktop: 'https://mail.qq.com/',
      mobile: 'https://w.mail.qq.com/',
      color: "#2D9FE2",
      icon: "QQmail"
    }]
  }, {
    name: "娱乐",
    buttons: [{
      name: "网易云音乐",
      desktop: 'https://music.163.com/',
      mobile: 'https://music.163.com/m/',
      color: "#D43C33",
      icon: "NeteaseMusic"
    }, {
      name: "Bilibili",
      desktop: 'https://www.bilibili.com/',
      mobile: 'https://m.bilibili.com/',
      color: "#DD5482",
      icon: "Bilibili"
    }, {
      name: "爱奇艺",
      desktop: 'http://www.iqiyi.com/',
      mobile: 'http://m.iqiyi.com/',
      color: "#5BA800",
      icon: "aiqiyi"
    }, {
      name: "优酷",
      desktop: 'http://youku.com/',
      mobile: 'http://youku.com/',
      color: "#2692FF",
      icon: "youku"
    }, {
      name: "YouTube",
      desktop: 'https://www.youtube.com/',
      mobile: 'https://m.youtube.com/',
      color: "#FF0000",
      icon: "youtube"
    }, {
      name: "虾米音乐",
      desktop: 'http://www.xiami.com/',
      mobile: 'http://h.xiami.com/',
      color: "#FF5E00",
      icon: "Music"
    }, {
      name: "AcFun",
      desktop: 'http://www.acfun.cn/',
      mobile: 'http://m.acfun.cn/',
      color: "#FD4C5B",
      icon: "acfun"
    }, {
      name: "腾讯视频",
      desktop: 'https://v.qq.com/',
      mobile: 'http://m.v.qq.com/',
      color: "#75CB10",
      icon: "TencentVideo"
    }, {
      name: "芒果TV",
      desktop: 'http://www.mgtv.com/',
      mobile: 'http://m.mgtv.com/#/channel/home',
      color: "#F06000",
      icon: "mgtv"
    }]
  }, {
    name: "购物",
    buttons: [{
      name: "淘宝",
      desktop: 'https://www.taobao.com/',
      mobile: 'https://m.taobao.com/#index',
      color: "#FF4018",
      icon: "Taobao"
    }, {
      name: "京东",
      desktop: 'https://www.jd.com/',
      mobile: 'https://m.jd.com/',
      color: "#E61C1A",
      icon: "JD"
    }, {
      name: "亚马逊",
      desktop: 'https://www.amazon.cn/',
      mobile: 'https://www.amazon.cn/',
      color: "#FF9B00",
      icon: "amazon"
    }, {
      name: "当当",
      desktop: 'http://www.dangdang.com/',
      mobile: 'http://m.dangdang.com/',
      color: "#F94F54",
      icon: "dangdang"
    }, {
      name: "唯品会",
      desktop: 'https://www.vip.com/',
      mobile: 'https://m.vip.com/',
      color: "#E3007E",
      icon: "weipinhui"
    }, {
      name: "网易严选",
      desktop: 'http://you.163.com/',
      mobile: 'http://m.you.163.com/?_stat_click_count=backwapbtn',
      color: "#A08D67",
      icon: "wangyiyanxuan"
    }]
  }]
}

const getters = {}

const mutations = {}

const actions = {}

export default {
  namespaced: true,
  state,
  getters,
  mutations,
  actions
}
